name: "Central Pipeline Example"
on:
  push:
  workflow_dispatch:
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Hello World
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./actions/hello-world
        id: hello
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
  # Still In Preview (Needs Custom Runner)
  # compose-example:
  #   runs-on: ubuntu-latest
  #   name: Compose Example
  #   steps:
  #     # To use this repository's private action,
  #     # you must check out the repository
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Hello world action step
  #       uses: ./actions/compose-example
